modLoader="javafml"
loaderVersion="[45,)"
license="GPLv3"

[[mods]]

modId="villagerflesh"
version="${file.jarVersion}"
displayName="Villager Flesh"
logoFile="logo.png"
authors="Lotkey"
description='''
Finally! Villagers drop their flesh. Now auto villager breeders have another use...
'''

[[dependencies.villagerflesh]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagerflesh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
