modLoader="javafml"
loaderVersion="[49.2.0,)"
license="GPLv3"

[[mods]]

modId="villagerflesh"
version="0.1"
displayName="Villager Flesh"
logoFile="logo.png"
authors="Lotkey"
description='''
Finally! Villagers drop their flesh. Now auto villager breeders have another use...
'''

[[dependencies.villagerflesh]]
    modId="forge"
    mandatory=true
    versionRange="[49.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagerflesh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
