name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: JDK Setup
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Fix Build Script Permissions
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
        name: Release ${{ github.ref_name }}
