name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Fix Script Permissions
      run: chmod +x ./gradlew

    - name: Build the mod
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: forge-mod
        path: build/libs/*.jar
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
        name: Release ${{ github.ref_name }}
